global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'php-app'
    static_configs:
      - targets: ['web:80']
    metrics_path: '/metrics.php'
  - job_name: 'mysqld'
    static_configs:
      - targets: [ 'mysqld_exporter:9104' ]
  - job_name: 'php-fpm'
    static_configs:
      - targets: [ 'php-fpm-exporter:9253' ]
  - job_name: 'nginx'
    static_configs:
      - targets: [ 'nginx-exporter:9113' ]
